### ISSUE TITLE
Provide Possbility to set Logger

### ISSUE THREAD

**Issue by vanthome** [htammen/n-odata-server#1]
Currently n-odata-server comes with log4js (which is not a common choice) but unfortunately, it's not possible to provide an own logger and neither it seems to be possible to even configure the existing one (which seems to create the file `n_odata_server.log`). This makes it hardly usable for a production scenario.

**Comment by htammen** [comment]
Come in and join the team.

**Comment by htammen** [comment]
I think the requester didn't mean to turn off logging at all. He wants to be more flexible in configuration and using his own logging framework which can be plugged into the application / n-odata-server module. At least he wants to be able to configure logging of n-odata-server, not only his application that is using this module.
The documentation for log4js configuration can be found [here](http://stritti.github.io/log4js/docu/users-guide.html#configuration)

**Comment by htammen** [comment]
Reverted all changes to logging behaviour cause fine grained logging configuration is already possible via log4js [logging configuration](https://github.com/htammen/n-odata-server#logging)

**Comment by htammen** [comment]
In a future release we might evaluate the configurable usage of other logging frameworks.
