### ISSUE TITLE
Authorization not checked in OData requests

### ISSUE THREAD

**Issue by renanwilliam** [htammen/n-odata-server#14]
If we have a end-point with protected access by ACL it's by-passed in OData requests

![image](https://zube.io/files/htammen/6d3ba75a4d70756f4e1562526a23e7e1.png)
Loopback API request

![Capturar2.jpg](https://zube.io/files/htammen/c7bacb2d821c4a3735980ecb23f22f02.jpeg)
n-odata-server request

**Comment by renanwilliam** [comment]
I think that can be solved with something like that:
```javascript
var oSharedMethod = ModelClass.sharedClass.find('find', true);
ModelClass.checkAccess(req.headers.authorization,"ModelName",oSharedMethod, loopback, function(param1, param2){
    console.log(param2);
});
```
I think something is missing.

**Comment by htammen** [comment]
OData services can now be protected with authorization functionality as described in [loopback documentation](https://docs.strongloop.com/display/public/LB/Authentication%2C+authorization%2C+and+permissions). Hiding methods is not supported yet, but ACLs work.

Implemented functionality in odata.ts. Cause we mainly leverage standard loopback functionality it should work for all use cases.

**Comment by renanwilliam** [comment]
I think that we have a problem when sending the token in Authorization header. I tried but the token is not set in req.accessToken, it is only in headers.authorization

**Comment by htammen** [comment]
I had a look at your changes and I would like to undo your change regarding AccessToken in odata.ts. The provisioning of the AccessToken in http request can be done by loopback configuration. This is documented somewhere in the loopback documentation and I think, cause it’s the recommended way, this should also be our way (relying on framework functionality as much as possible). I’m talking about this change
```
  //Needs to instantiate the AccessToken Model first
 this.getAccessTokenInstance(req, res).then(() => {
```
I think it's sufficient to add this line to your middleware.json file directly after the "initial" and "session" sections 
```
  "auth": {
    "loopback#token": {}
  },
```
This is documented [here](http://apidocs.strongloop.com/loopback/#loopback-token)

If you need to access the AccessToken and other context information in your application you can use the `loopback-context` module. This is documented [here](https://docs.strongloop.com/display/APIC/Using+current+context?src=search#)

Can you please undo your AccessToken changes and test it with the above mentioned setting?
