### ISSUE TITLE
Do not expose non-Public Models

### ISSUE THREAD

**Issue by vanthome** [htammen/n-odata-server#2]
Currently, n-data-server seems to expose also models which are set to non-public like this:

```
  "ACL": {
    "dataSource": "db",
    "public": false
  },
```

To be in-line with loopback, this should not be the case.

**Comment by htammen** [comment]
Have that already on the list but with minor priority cause I'm currently using this package not for productive purposes. You're welcome to implement it.

**Comment by renanwilliam** [comment]
As we have authorization cover in #22, is it necessary insert a handling to check if model is public in each operation?
