### ISSUE TITLE
Include $format=xls to export entity data to Excel

### ISSUE THREAD

**Issue by renanwilliam** [htammen/n-odata-server#27]
Include a feature to support $format=xsl to export the result to MS Excel

**Comment by htammen** [comment]
Don't see this as function that n-odata-server should provide. OData specification defines export as JSON and XML. I would like to concentrate on the raw OData specification functionalities.

**Comment by renanwilliam** [comment]
In OData specification document there's no mention to strict the format only to JSON or Atom: http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752365
 
I think that you're right to focus on the 'basic' of protocol but let's keep it in radar because after include the custom notations this feature
will be very requested.

I think that is a very important feature for who wants to work with UI5 SmartControls (is the implementation default for export to Excel function). And the implementation of this feature is very simple.

It's a specification about that here: https://help.sap.com/saphelp_nw74/helpdata/en/a2/4c8490449041b88b7890d299b57351/content.htm
