### ISSUE TITLE
DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by igorabelev** [htammen/n-odata-server#36]
Dear Mr. Tammen,

first of all thank you for this module. 
I am trying to setup the node.js based ODATA server and experiencing the problem described below:

1. I have setup the loopback
2. I have installed the n-odata-server (according to the help)
3. I have configured the app according to the description
4. I am able to call http://localhost:3000/odata/, and I am getting the proper respond
5. I am able to call the http://localhost:3000/odata/MyEntitySet, and I am getting the proper respond
6. But when I am calling  http://localhost:3000/odata/$metdata, I am getting the error:

[2017-12-08 21:03:49.464] [ERROR] console - (node:2489) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Missing attribute value for attribute Type of element Property

As the result I cannot properly work with the odata server. Target is in final end to use the server in conjunction with openui5/sapui5 app using ODATA.

I thank you in advance for the help
Best Regards / Mit freundlichen Grüßen
Igor Abelev
node verion = 9.0.0
n-odata version = 0.4.1

**Comment by igorabelev** [comment]
Dear Mr. Tammen,

after debugging I have realized that the error occurred because of the standard Loopback Data Model: AccessToken
The XMLNode.js does not able to cope with the properties, which are not defined.

This property "scope" of the Data Model  AccessToken is passed with the empty @Type  into the XMLNode.js module.exports = XMLNode = (function() { }
with the undefined @Type. I suppose that when creating the "name" Object the option having the property as array is not considered....

Is there any possibility to solve/obviate the problem

Thank you & Best Regards, Igor Abelev

{
  "name": "AccessToken",
  "properties": {
    "id": {
      "type": "string",
      "id": true
    },
    "ttl": {
      "type": "number",
      "ttl": true,
      "default": 1209600,
      "description": "time to live in seconds (2 weeks by default)"
    },
    "scopes": {
      "type": ["string"],
      "description": "Array of scopes granted to this access token."
    },
    "created": {
      "type": "Date",
      "defaultFn": "now"
    }
  },
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "User",
      "foreignKey": "userId"
    }
  },
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "property": "create",
      "permission": "ALLOW"
    }
  ]
}

**Comment by renanwilliam** [comment]
Hi @igorabelev ,

What is your loopback version?

**Comment by igorabelev** [comment]
Hi @renanwilliam 

Thank you for your respond, the used loopback version is:
This the fragment out of the my package.json:
"loopback": "^3.0.0",
"loopback-boot": "^2.6.5",
"loopback-component-explorer": "^4.0.0",

Thank you & Best Regards, 
Igor Abelev

**Comment by renanwilliam** [comment]
Hi @igorabelev ,

Could you try the 2.x.x version?
My packjage.json:
```json 
"dependencies": {
    "bcrypt": "^1.0.1",
    "compression": "^1.0.11",
    "connect-ensure-login": "^0.1.1",
    "cookie-parser": "^1.3.2",
    "cors": "^2.5.2",
    "errorhandler": "^1.1.1",
    "express-flash": "0.0.2",
    "express-session": "^1.7.6",
    "helmet": "^1.3.0",
    "jade": "^1.7.0",
    "loopback": "^2.0.0",
    "loopback-boot": "^2.23.0",
    "loopback-component-explorer": "^2.7.*",
    "loopback-component-passport": "^2.3.0",
    "loopback-connector-mongodb": "^1.17.*",
    "loopback-connector-mysql": "^2.4.0",
    "loopback-context": "^1.0.0",
    "n-odata-server": "^0.4.1",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^1.1.1"
  }
```
