### ISSUE TITLE
Loopback V3 With $metadata Issue

### ISSUE THREAD

**Issue by umayaraj** [htammen/n-odata-server#40]
Hi , i try to get meta data from loopback v3 
1) i can access /odata/$metadata without User and AccessToken in model-config.json
![Loopback V3 odata Work](https://user-images.githubusercontent.com/52098245/72208024-38d5ee00-34c4-11ea-9e56-37136d006c1a.png)

2)if i put User and AccessToken in model-config.json i get bellow error
![LoopbackV3 With nodataserver](https://user-images.githubusercontent.com/52098245/72207962-6706fe00-34c3-11ea-94ab-c3bc07e48ed5.png)

Please give guide to solve this issue 
thanks & regards 
umayaraj.b

**Comment by htammen** [comment]
Sorry but I stopped development on this package cause of lack of response. If you find a solution fix it and send a PR with documentation. I will then merge this into the repo.
